import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  tutorialSidebar: [
    'intro',//这里是设置单独的界面
    // 'hello',
    {
      type: 'category',
      label: '使用手册',
      items: [
        'tutorial-basics/APU 服务器使用手册',
        'tutorial-basics/APU服务器对比测试报告V1.0',
        // 'tutorial-basics/APU高性能计算服务器产品应用案例'
      ],
    },
  ],

};

export default sidebars;
